### ISSUE TITLE
Modify Serial accessory

### ISSUE THREAD

**Issue by 5chacha5** [lapixo/homebridge-bsblan-thermostat#3]
Hi,

how I can modify the serial accessory of my 2 accessories to generate 2 devices in Home assistant ?

For example :  "Serial": "BSBThermostat0" did not work

Thanks a lot

**Comment by lapixo** [comment]
You can not change the accessory name! This should be "BSBThermostat"

If you want have two devices, please look at the examples like:
  "accessories": [
        {
            "accessory": "BSBThermostat",
            "name": "Thermostat-HK1",
            "apiroute": "http://1.1.1.1",
            "pollInterval": 35
        },
        {
            "accessory": "BSBThermostat",
            "name": "Thermostat-TW",
            "apiroute": "http://2.2.2.2",
            "pollInterval": 50,
            "isDHW": true
        }
    ],


This generates two thermostat accessories (devices).

**Comment by 5chacha5** [comment]
ok but I have 2 circuit with one Arduino BSB LAN :-(

so only one http

**Comment by lapixo** [comment]
This is no problem! You can use the same IP for both accessories.
But set the poolInterval to different values like the example above.

**Comment by 5chacha5** [comment]
yes that's work in home bridge but I want to import them to home assistant and only one thermostat is create ; to IOS directly from home bridge that's ok

**Comment by lapixo** [comment]
This Plugin is only made for homebridge+homekit. I don't know how home Assistant works sry. 

how do you import the devices from homebridge to home assistant?

**Comment by 5chacha5** [comment]
to have all my devices in HA :-)

thanks for your help

**Comment by 5chacha5** [comment]
Hi 

can I try to rewrite your plugin for my need ? I'm new with GitHub but I want to try :-)

**Comment by lapixo** [comment]
This is open source. You can do what you want ;)
