### ISSUE TITLE
Error getting status: Parse Error: Invalid header value char

### ISSUE THREAD

**Issue by 5chacha5** [lapixo/homebridge-bsblan-thermostat#7]
Hi,

I don't know why but I have this error when getstatus is launch ? perhaps a update of homebridge ?

Error getting status: Parse Error: Invalid header value char

what I can do ?

Thanks

**Comment by lapixo** [comment]
Hi, sorry I don’t Use this Plugin Anymore. I have no time to develop it. Feel free to make you own.

I have switched to Home Assistant where you can publish every device to HomeKit. ;)
